//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerRelations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerNote
    {
        public int NoteId { get; set; }
        public int CustomerId { get; set; }
        public int UserId { get; set; }
        public string NoteText { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
