//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace CustomerRelations.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Customer
    {
        public Customer()
        {
            this.CustomerNotes = new HashSet<CustomerNote>();
        }

        public int CustomerId { get; set; }

        [Required(ErrorMessage = "Please enter First Name")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Please enter Last Name")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Please enter Email Address")]
        [RegularExpression(".+@.+\\..+", ErrorMessage = "Please enter a valid Email Address. (eg. a@a.com")]
        public string EMail { get; set; }

        [Required(ErrorMessage = "Please enter Address")]
        public string AddressLine1 { get; set; }

        public string AddressLine2 { get; set; }

        [Required(ErrorMessage = "Please enter City")]
        public string City { get; set; }

        
        [Required(ErrorMessage = "Please enter State")]
        [RegularExpression("^[A-Z]{2}$", ErrorMessage = "Please enter a valid State (e.g. TX)")]
        public string State { get; set; }

        [Required(ErrorMessage = "Please enter Telephone")]
        [RegularExpression("^\\d{10}$", ErrorMessage = "Please enter a valid 10 digit Telephone")]
        public string Telephone { get; set; }

        public byte[] Picture { get; set; }

        [Required(ErrorMessage = "Please enter Zip Code")]
        [RegularExpression("^\\d{5}$", ErrorMessage = "Please enter a valid 5 digit ZipCode")]
        public string ZipCode { get; set; }

        public int UserId { get; set; }
        public System.DateTime CreatedDate { get; set; }

        public virtual UserProfile UserProfile { get; set; }
        public virtual ICollection<CustomerNote> CustomerNotes { get; set; }
    }

}
